import { Question, RoundType } from "./types";

// 4 gói câu hỏi Khởi động, mỗi gói 12 câu
export const khoiDongPackages: Question[][] = [
  // Gói 1
  [
    { id: "kd-p1-1", text: "Thủ đô của Việt Nam là thành phố nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-2", text: "Ngọn núi cao nhất Việt Nam là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-3", text: "Sông nào dài nhất Việt Nam?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-4", text: "Năm 2024 là năm con gì theo âm lịch?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-5", text: "Ai là tác giả của truyện 'Dế Mèn phiêu lưu ký'?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-6", text: "Hành tinh nào gần Mặt Trời nhất?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-7", text: "Số nguyên tố nhỏ nhất là số nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-8", text: "Thành phố nào được mệnh danh là 'Thành phố Hoa'?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-9", text: "Quốc gia nào có diện tích lớn nhất thế giới?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-10", text: "Ai là người đầu tiên đặt chân lên Mặt Trăng?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-11", text: "Nguyên tố hóa học nào có ký hiệu là 'Au'?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p1-12", text: "Tác phẩm 'Truyện Kiều' là của ai?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
  ],
  // Gói 2
  [
    { id: "kd-p2-1", text: "Loài động vật nào lớn nhất trên Trái Đất?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-2", text: "Số Pi (π) xấp xỉ bằng bao nhiêu?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-3", text: "Thành phố nào được gọi là 'Thành phố không ngủ'?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-4", text: "Ngày Quốc khánh Việt Nam là ngày nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-5", text: "Cơ quan nào trong cơ thể người lớn nhất?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-6", text: "World Cup đầu tiên được tổ chức ở đâu?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-7", text: "Sông nào chảy qua nhiều quốc gia nhất?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-8", text: "Chiến thắng Điện Biên Phủ diễn ra vào năm nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-9", text: "Tốc độ ánh sáng trong chân không là bao nhiêu?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-10", text: "'Chí Phèo' là tác phẩm của nhà văn nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-11", text: "Công thức tính diện tích hình tròn là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p2-12", text: "Thành phố cổ nào ở miền Trung nổi tiếng với phố cổ?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
  ],
  // Gói 3
  [
    { id: "kd-p3-1", text: "Loài hoa nào là biểu tượng của Việt Nam, màu vàng, nở vào mùa thu?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-2", text: "Loại bánh truyền thống làm từ gạo nếp, có nhân đậu xanh là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-3", text: "Loại nhạc cụ dây, có 4 dây, dùng để kéo là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-4", text: "Môn thể thao dùng vợt và quả cầu lông là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-5", text: "Loài động vật có vú sống dưới nước, rất thông minh là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-6", text: "Loại cây trồng phổ biến ở Việt Nam, có màu xanh, dùng để nấu canh là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-7", text: "Loại quả màu đỏ, có nhiều hạt, ăn rất ngọt là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-8", text: "Tác phẩm 'Nhật ký trong tù' là của ai?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-9", text: "Hành tinh nào có vành đai nổi tiếng?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-10", text: "Ngọn núi cao nhất thế giới là gì?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-11", text: "Đại dương nào lớn nhất thế giới?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p3-12", text: "Thủ đô của Pháp là thành phố nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
  ],
  // Gói 4
  [
    { id: "kd-p4-1", text: "Thủ đô của Nhật Bản là thành phố nào?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-2", text: "Kim tự tháp lớn nhất nằm ở đâu?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-3", text: "Quốc gia nào có dân số đông nhất thế giới?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-4", text: "Ngôn ngữ nào được nói nhiều nhất thế giới?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-5", text: "Tác phẩm 'Romeo và Juliet' là của ai?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-6", text: "Hệ mặt trời có bao nhiêu hành tinh?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-7", text: "Ngày nào được gọi là 'Ngày Trái Đất'?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-8", text: "Loài chim nào không biết bay nhưng bơi rất giỏi?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-9", text: "Thành phố nào được gọi là 'Thành phố ánh sáng'?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-10", text: "Nước nào có nhiều múi giờ nhất?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-11", text: "Loài động vật nào sống lâu nhất trên Trái Đất?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
    { id: "kd-p4-12", text: "Ngọn núi lửa cao nhất thế giới nằm ở đâu?", points: 10, timeLimitSec: 15, round: "khoi-dong", isOpenEnded: true },
  ],
];

export const questions: Record<RoundType, Question[]> = {
  "khoi-dong": [], // Không dùng nữa, dùng khoiDongPackages thay thế
  "vuot-chuong-ngai-vat": [
    {
      id: "vcnv-1",
      text: "Từ khóa: Đây là một loại cây trồng phổ biến ở Việt Nam, có màu xanh, dùng để nấu canh.",
      options: [
        { label: "A", text: "Rau muống" },
        { label: "B", text: "Rau cải" },
        { label: "C", text: "Rau dền" },
        { label: "D", text: "Rau ngót" },
      ],
      correctIndex: 0,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-2",
      text: "Từ khóa: Đây là một loài động vật có vú sống dưới nước, rất thông minh.",
      options: [
        { label: "A", text: "Cá heo" },
        { label: "B", text: "Cá mập" },
        { label: "C", text: "Cá voi" },
        { label: "D", text: "Cá sấu" },
      ],
      correctIndex: 0,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-3",
      text: "Từ khóa: Đây là một môn thể thao dùng vợt và quả cầu lông.",
      options: [
        { label: "A", text: "Bóng bàn" },
        { label: "B", text: "Cầu lông" },
        { label: "C", text: "Tennis" },
        { label: "D", text: "Bóng chuyền" },
      ],
      correctIndex: 1,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-4",
      text: "Từ khóa: Đây là một loại nhạc cụ dây, có 4 dây, dùng để kéo.",
      options: [
        { label: "A", text: "Đàn guitar" },
        { label: "B", text: "Đàn violin" },
        { label: "C", text: "Đàn bầu" },
        { label: "D", text: "Đàn nhị" },
      ],
      correctIndex: 3,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-5",
      text: "Từ khóa: Đây là một loại quả màu đỏ, có nhiều hạt, ăn rất ngọt.",
      options: [
        { label: "A", text: "Dưa hấu" },
        { label: "B", text: "Dâu tây" },
        { label: "C", text: "Cherry" },
        { label: "D", text: "Lựu" },
      ],
      correctIndex: 0,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-6",
      text: "Từ khóa: Đây là một thành phố cổ ở miền Trung, nổi tiếng với phố cổ.",
      options: [
        { label: "A", text: "Hội An" },
        { label: "B", text: "Huế" },
        { label: "C", text: "Đà Nẵng" },
        { label: "D", text: "Quy Nhơn" },
      ],
      correctIndex: 0,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-7",
      text: "Từ khóa: Đây là một loại bánh truyền thống, làm từ gạo nếp, có nhân đậu xanh.",
      options: [
        { label: "A", text: "Bánh chưng" },
        { label: "B", text: "Bánh tét" },
        { label: "C", text: "Bánh dày" },
        { label: "D", text: "Bánh giò" },
      ],
      correctIndex: 0,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
    {
      id: "vcnv-8",
      text: "Từ khóa: Đây là một loài hoa biểu tượng của Việt Nam, màu vàng, nở vào mùa thu.",
      options: [
        { label: "A", text: "Hoa sen" },
        { label: "B", text: "Hoa mai" },
        { label: "C", text: "Hoa đào" },
        { label: "D", text: "Hoa cúc" },
      ],
      correctIndex: 1,
      points: 20,
      timeLimitSec: 30,
      round: "vuot-chuong-ngai-vat",
    },
  ],
  "tang-toc": [
    {
      id: "tt-1",
      text: "Ai là người đầu tiên đặt chân lên Mặt Trăng?",
      options: [
        { label: "A", text: "Neil Armstrong" },
        { label: "B", text: "Buzz Aldrin" },
        { label: "C", text: "Michael Collins" },
        { label: "D", text: "Yuri Gagarin" },
      ],
      correctIndex: 0,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-2",
      text: "Thành phố nào được gọi là 'Thành phố không ngủ'?",
      options: [
        { label: "A", text: "New York" },
        { label: "B", text: "Tokyo" },
        { label: "C", text: "London" },
        { label: "D", text: "Paris" },
      ],
      correctIndex: 0,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-3",
      text: "Nguyên tố hóa học nào có ký hiệu là 'Au'?",
      options: [
        { label: "A", text: "Bạc" },
        { label: "B", text: "Vàng" },
        { label: "C", text: "Đồng" },
        { label: "D", text: "Sắt" },
      ],
      correctIndex: 1,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-4",
      text: "Tác phẩm 'Nhật ký trong tù' là của ai?",
      options: [
        { label: "A", text: "Hồ Chí Minh" },
        { label: "B", text: "Tố Hữu" },
        { label: "C", text: "Xuân Diệu" },
        { label: "D", text: "Huy Cận" },
      ],
      correctIndex: 0,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-5",
      text: "Số Pi (π) xấp xỉ bằng bao nhiêu?",
      options: [
        { label: "A", text: "3.14" },
        { label: "B", text: "3.14159" },
        { label: "C", text: "3.14159265359" },
        { label: "D", text: "Tất cả đều đúng" },
      ],
      correctIndex: 3,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-6",
      text: "Loài động vật nào lớn nhất trên Trái Đất?",
      options: [
        { label: "A", text: "Cá voi xanh" },
        { label: "B", text: "Voi châu Phi" },
        { label: "C", text: "Cá mập trắng" },
        { label: "D", text: "Hươu cao cổ" },
      ],
      correctIndex: 0,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-7",
      text: "Nước nào có diện tích lớn nhất thế giới?",
      options: [
        { label: "A", text: "Canada" },
        { label: "B", text: "Trung Quốc" },
        { label: "C", text: "Nga" },
        { label: "D", text: "Mỹ" },
      ],
      correctIndex: 2,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
    {
      id: "tt-8",
      text: "Ai là tác giả của 'Truyện Kiều'?",
      options: [
        { label: "A", text: "Nguyễn Du" },
        { label: "B", text: "Nguyễn Trãi" },
        { label: "C", text: "Hồ Xuân Hương" },
        { label: "D", text: "Cao Bá Quát" },
      ],
      correctIndex: 0,
      points: 30,
      timeLimitSec: 20,
      round: "tang-toc",
    },
  ],
  "ve-dich": [
    {
      id: "vd-1",
      text: "Câu hỏi về địa lý: Sông nào chảy qua nhiều quốc gia nhất?",
      options: [
        { label: "A", text: "Sông Nile" },
        { label: "B", text: "Sông Amazon" },
        { label: "C", text: "Sông Danube" },
        { label: "D", text: "Sông Mê Kông" },
      ],
      correctIndex: 2,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-2",
      text: "Câu hỏi về lịch sử: Chiến thắng Điện Biên Phủ diễn ra vào năm nào?",
      options: [
        { label: "A", text: "1953" },
        { label: "B", text: "1954" },
        { label: "C", text: "1955" },
        { label: "D", text: "1956" },
      ],
      correctIndex: 1,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-3",
      text: "Câu hỏi về khoa học: Tốc độ ánh sáng trong chân không là bao nhiêu?",
      options: [
        { label: "A", text: "300,000 km/s" },
        { label: "B", text: "299,792,458 m/s" },
        { label: "C", text: "3 x 10^8 m/s" },
        { label: "D", text: "Tất cả đều đúng" },
      ],
      correctIndex: 3,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-4",
      text: "Câu hỏi về văn học: 'Chí Phèo' là tác phẩm của nhà văn nào?",
      options: [
        { label: "A", text: "Nam Cao" },
        { label: "B", text: "Vũ Trọng Phụng" },
        { label: "C", text: "Nguyễn Công Hoan" },
        { label: "D", text: "Nguyên Hồng" },
      ],
      correctIndex: 0,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-5",
      text: "Câu hỏi về toán học: Công thức tính diện tích hình tròn là?",
      options: [
        { label: "A", text: "πr²" },
        { label: "B", text: "2πr" },
        { label: "C", text: "πd" },
        { label: "D", text: "r²" },
      ],
      correctIndex: 0,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-6",
      text: "Câu hỏi về thể thao: World Cup đầu tiên được tổ chức ở đâu?",
      options: [
        { label: "A", text: "Brazil" },
        { label: "B", text: "Uruguay" },
        { label: "C", text: "Italy" },
        { label: "D", text: "Pháp" },
      ],
      correctIndex: 1,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-7",
      text: "Câu hỏi về sinh học: Cơ quan nào trong cơ thể người lớn nhất?",
      options: [
        { label: "A", text: "Gan" },
        { label: "B", text: "Phổi" },
        { label: "C", text: "Da" },
        { label: "D", text: "Ruột" },
      ],
      correctIndex: 2,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
    {
      id: "vd-8",
      text: "Câu hỏi tổng hợp: Ngày Quốc khánh Việt Nam là ngày nào?",
      options: [
        { label: "A", text: "30/4" },
        { label: "B", text: "1/5" },
        { label: "C", text: "2/9" },
        { label: "D", text: "19/5" },
      ],
      correctIndex: 2,
      points: 40,
      timeLimitSec: 30,
      round: "ve-dich",
    },
  ],
};

export const roundNames: Record<RoundType, string> = {
  "khoi-dong": "Vòng 1: Khơi nguồn năng lượng",
  "vuot-chuong-ngai-vat": "Vòng 2: Hành trình giọt dầu",
  "tang-toc": "Vòng 3: Tăng tốc vận hành",
  "ve-dich": "Vòng 4: Chinh phục đỉnh cao",
};

